### ISSUE TITLE
Tikz

### ISSUE THREAD

**Issue by GG1991** [GG1991/nfpe#4]
pdf2svg should be install on elisya server in order to see the tikz figures.

**Comment by simoncarrignon** [comment]
I installed  it on the server. Telle me if it's good now!

**Comment by GG1991** [comment]
where do i recompile the corresponding branch ?

**Comment by simoncarrignon** [comment]
if you login with the bsc user (`ssh bsc@elisya.org`) you can see in the pos-receive hook how are compiled each branch when we do the push. The file is that one:
`~/nfpe.git/hooks/post-receive`

the line that intereste you is that one:
```bash
        bundle exec jekyll build -s . -d ../html-"$branch"
```
with `branch=thenameofthebranchyouwanttocompile`.

But honestly me what I will do is just to push a "false" commit (where I just add one blank line to a file)  and check the result

**Comment by GG1991** [comment]
Thank you Simon, give me permissions man:
jekyll 3.4.3 | Error:  Permission denied @ rb_sysopen - /data/www/elisya/bsc/html-guido/404.html

**Comment by GG1991** [comment]
it continues not working login as bsc did not work and false commit to reset server too.

**Comment by simoncarrignon** [comment]
I just did:
```bash
ssh bsc@elisya.org
cd nfpe
git checkout guido
 bundle exec jekyll build -s . -d ../html-guido/
```

And it worked fine:

![imagen](https://cloud.githubusercontent.com/assets/4749455/26309946/502270aa-3eff-11e7-867f-4c89a3b42f7f.png)

**Comment by GG1991** [comment]
great Simon ! surelly I was missing something. I
